spring:
  #???????
  datasource:
    #???????
    type: com.zaxxer.hikari.HikariDataSource
    #?????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ums?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  #redis
  redis:
    port: 6379
    host: localhost


#????
logging:
  level:
    com.example: debug

server:
  port: 8081

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  #定义别名
  type-aliases-package: com.example.*.pojo
